# Generated by Django 2.1.3 on 2019-08-03 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True, default='')),
                ('job', models.CharField(blank=True, default='', max_length=150)),
                ('age', models.CharField(blank=True, default='', max_length=150)),
                ('country', models.CharField(blank=True, default='', max_length=150)),
                ('facebook', models.URLField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='')),
                ('twitter', models.URLField(blank=True, default='')),
                ('personal_website', models.URLField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
