# Generated by Django 2.2.4 on 2019-08-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190821_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='notify_when_comment',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='notify_when_reply',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
