# Generated by Django 2.2.4 on 2019-08-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
