# Generated by Django 2.2.4 on 2019-08-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
